const stub = {
  categories: [
    { id: 9, name: 'General Knowledge' },
    { id: 10, name: 'Entertainment: Books' },
    { id: 11, name: 'Entertainment: Film' },
    { id: 12, name: 'Entertainment: Music' },
    { id: 13, name: 'Entertainment: Musicals & Theatres' },
    { id: 14, name: 'Entertainment: Television' },
    { id: 15, name: 'Entertainment: Video Games' },
    { id: 16, name: 'Entertainment: Board Games' },
    { id: 17, name: 'Science & Nature' },
    { id: 18, name: 'Science: Computers' },
    { id: 19, name: 'Science: Mathematics' },
    { id: 20, name: 'Mythology' },
    { id: 21, name: 'Sports' },
    { id: 22, name: 'Geography' },
    { id: 23, name: 'History' },
    { id: 24, name: 'Politics' },
    { id: 25, name: 'Art' },
    { id: 26, name: 'Celebrities' },
    { id: 27, name: 'Animals' },
    { id: 28, name: 'Vehicles' },
    { id: 29, name: 'Entertainment: Comics' },
    { id: 30, name: 'Science: Gadgets' },
    { id: 31, name: 'Entertainment: Japanese Anime & Manga' },
    { id: 32, name: 'Entertainment: Cartoon & Animations' }
  ],

  questions: [
    {
      question: 'Which of these countries is located the FURTHEST away from the South China Sea?',
      category: 'Geography',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Bangladesh',
      incorrect_ans_1: 'Malaysia',
      incorrect_ans_2: 'Vietnam',
      incorrect_ans_3: 'Philippines',
    },
    {
      question: 'Disney&#039;s Haunted Mansion is home to a trio of Hitchhiking Ghosts. Which of these is NOT one of them?',
      category: 'General Knowledge',
      type: 'multiple',
      difficulty: 'hard',
      correct_ans: 'Harry',
      incorrect_ans_1: 'Gus',
      incorrect_ans_2: 'Phineas',
      incorrect_ans_3: 'Ezra',
    },
    {
      question: 'The main protagonist of the fifth part of JoJo&#039;s Bizarre Adventure is which of the following?',
      category: 'Entertainment: Japanese Anime & Manga',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Giorno Giovanna',
      incorrect_ans_1: 'Guido Mista',
      incorrect_ans_2: 'Jonathan Joestar',
      incorrect_ans_3: 'Joey JoJo',
    },
    {
      question: 'In Pre-Super Genesis universe of &quot;Sonic the Hedgehog&quot; comic, what was the name of  Sally Acorn&#039;s brother?',
      category: 'Entertainment: Comics',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Elias Acorn',
      incorrect_ans_1: 'Maximillian Acorn',
      incorrect_ans_2: 'Alexis Acorn',
      incorrect_ans_3: 'Frederick Acorn',
    },
    {
      question: '.at is the top-level domain for what country?',
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Austria',
      incorrect_ans_1: 'Argentina',
      incorrect_ans_2: 'Australia',
      incorrect_ans_3: 'Angola',
    },
    {
      question: 'Toby Fox&#039;s &quot;Megalovania&quot; was first used where?',
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Radiation&#039;s Earthbound Halloween Hack',
      incorrect_ans_1: 'Homestuck: [S] Wake',
      incorrect_ans_2: 'Undertale',
      incorrect_ans_3: 'Mother: Cognitive Dissonance',
    },
    {
      question: 'Who voices &quot;Shou Suzuki&quot; in the English dub of &quot;Mob Psycho 100&quot;?',
      category: 'Entertainment: Japanese Anime & Manga',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Casey Mongillo',
      incorrect_ans_1: 'Ben Diskin',
      incorrect_ans_2: 'Chris Niosi',
      incorrect_ans_3: 'David Naughton',
    },
    {
      question: 'In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.',
      category: 'Entertainment: Video Games',
      type: 'boolean',
      difficulty: 'medium',
      correct_ans: 'True',
      incorrect_ans_1: 'False',
      incorrect_ans_2: undefined,
      incorrect_ans_3: undefined,
    },
    {
      question: 'The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?',
      category: 'Entertainment: Video Games',
      type: 'boolean',
      difficulty: 'easy',
      correct_ans: 'True',
      incorrect_ans_1: 'False',
      incorrect_ans_2: undefined,
      incorrect_ans_3: undefined,
    },
    {
      question: 'In &quot;Little Witch Academia&quot;, what is Shiny Chariot&#039;s alias at Luna Nova Academy?',
      category: 'Entertainment: Japanese Anime & Manga',
      type: 'multiple',
      difficulty: 'medium',
      correct_ans: 'Ursula Callistis',
      incorrect_ans_1: 'Croix Meridies',
      incorrect_ans_2: 'Miranda Holbrook',
      incorrect_ans_3: 'Anne Finnelan',
    },
  ]
};

module.exports = stub;
